apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: argo
  labels: 
    app: nginx
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
      nodePort: 31755